<a href="https://colab.research.google.com/github/sumanrbt/pytorch-practice/blob/master/RNNbasic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
from torch import nn
from torch.autograd import Variable



In [0]:
lstm = nn.LSTM(4, 4,batch_first=True)
print(lstm.weight_hh_l0.shape)

torch.Size([16, 4])


In [0]:
class Model(nn.Module):
    def __init__(self,batch_size=1,num_classes=5,
                 input_size=5,hidden_size=5,seq_len=1,num_layers=1):
        super(Model,self).__init__()
        self.lstm=nn.LSTM(5,5,batch_first=True)
        self.batch_size=batch_size
        self.num_classes=num_classes
        self.input_size=input_size
        self.hidden_size=hidden_size
        self.seq_len=seq_len
        self.num_layers=num_layers

    def forward(self,x,hidden):
        x=x.view(batch_size,seq_len,input_size)
        out,hidden=self.lstm(x,hidden)
        return out,hidden
        

In [0]:

char=["H","I","E","L","O",]
import numpy as np
#print(char2int)
def OneHotEncode(char,chars,n_labels):
    char2int={inn:char for char,inn in enumerate(chars)}
    a=np.zeros(n_labels)
    a[char2int[char]]=1
    return a
print(OneHotEncode("H",char,len(char)))
inputs=torch.Tensor([OneHotEncode(l,char,len(char)) for l in ["H","I","H","E","L","L"] ]).view(1,6,5)
y_label=torch.Tensor([OneHotEncode(l,char,len(char)) for l in ["I","H","E","L","L","O"] ]).view(1,6,5)
print("inputs\n",inputs,"\n\n\n",y_label)


[1. 0. 0. 0. 0.]
inputs
 tensor([[[1., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [1., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0.],
         [0., 0., 0., 1., 0.],
         [0., 0., 0., 1., 0.]]]) 


 tensor([[[0., 1., 0., 0., 0.],
         [1., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0.],
         [0., 0., 0., 1., 0.],
         [0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 1.]]])


In [0]:
model=Model()

In [0]:
hidden = (torch.randn(1, 1, 5),torch.randn(1, 1, 5))
s=inputs[0]

print(s[0])
out,hidden=model.forward(s[0],hidden)

tensor([1., 0., 0., 0., 0.])


In [0]:
print(out)

tensor([[[-0.1919, -0.3889, -0.0182,  0.1602,  0.2346]]],
       grad_fn=<TransposeBackward0>)
